CREATE DATABASE funcionariosdb;

\c funcionariosdb;

CREATE TABLE departamentos (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE funcionarios (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    cidade VARCHAR(100) NOT NULL,
    departamento_id INTEGER REFERENCES departamentos(id) ON DELETE SET NULL
);

ALTER TABLE funcionarios ADD COLUMN photo TEXT;

INSERT INTO departamentos (name) VALUES 
    ('Financeiro'),
    ('Producao'),
    ('Logistica'),
    ('Marketing e Vendas'),
    ('Administracao');

INSERT INTO funcionarios (name, cidade, departamento_id, photo) VALUES 
    ('Kevin', 'Hortolandia', 5, '/image/kevinUser.png'),
    ('Jade', 'Sao Paulo', 1, '/image/jadeUser.png'),
    ('Beatriz', 'Sao Paulo', 2, null),
    ('Larissa', 'Vinhedo', 3, null),
    ('Guilherme', 'Vinhedo', 4, null),
    ('Carlos', 'Campinas', 1, null),
    ('Mariana', 'Valinhos', 2, null),
    ('João', 'Vinhedo', 3, null),
    ('Paula', 'Hortolandia', 4, null),
    ('Rafael', 'Sao Paulo', 5, null),
    ('Camila', 'Campinas', 1, null),
    ('Thiago', 'Valinhos', 2, null),
    ('Vanessa', 'Vinhedo', 3, null),
    ('Felipe', 'Hortolandia', 4, null),
    ('Aline', 'Sao Paulo', 5, null),
    ('Bruno', 'Campinas', 1, null),
    ('Larissa', 'Valinhos', 2, null),
    ('Renato', 'Vinhedo', 3, null),
    ('Juliana', 'Hortolandia', 4, null),
    ('Pedro', 'Sao Paulo', 5, null),
    ('Sofia', 'Campinas', 1, null),
    ('Lucas', 'Valinhos', 2, null),
    ('Isabela', 'Vinhedo', 3, null),
    ('Henrique', 'Hortolandia', 4, null),
    ('Carolina', 'Sao Paulo', 5, null),
    ('Eduardo', 'Campinas', 1, null),
    ('Fernanda', 'Valinhos', 2, null),
    ('Rodrigo', 'Vinhedo', 3, null),
    ('Patricia', 'Hortolandia', 4, null),
    ('André', 'Sao Paulo', 5, null),
    ('Gabriela', 'Campinas', 1, null),
    ('Marcelo', 'Valinhos', 2, null),
    ('Tatiana', 'Vinhedo', 3, null),
    ('Diego', 'Hortolandia', 4, null),
    ('Ana Clara', 'Sao Paulo', 5, null),
    ('Leonardo', 'Campinas', 1, null),
    ('Beatriz', 'Valinhos', 2, null),
    ('Ricardo', 'Vinhedo', 3, null),
    ('Luana', 'Hortolandia', 4, null),
    ('Gustavo', 'Sao Paulo', 5, null),
    ('Natália', 'Campinas', 1, null),
    ('Fábio', 'Valinhos', 2, null),
    ('Débora', 'Vinhedo', 3, null),
    ('Maurício', 'Hortolandia', 4, null),
    ('Cecília', 'Sao Paulo', 5, null),
    ('Rogério', 'Campinas', 1, null),
    ('Amanda', 'Valinhos', 2, null),
    ('Vitor', 'Vinhedo', 3, null),
    ('Elaine', 'Hortolandia', 4, null),
    ('Otávio', 'Sao Paulo', 5, null),
    ('Simone', 'Campinas', 1, null),
    ('Daniel', 'Valinhos', 2, null),
    ('Priscila', 'Vinhedo', 3, null),
    ('Alexandre', 'Hortolandia', 4, null),
    ('Michele', 'Sao Paulo', 5, null),
    ('Rafael', 'Campinas', 1, null),
    ('Carla', 'Valinhos', 2, null),
    ('Fernando', 'Vinhedo', 3, null),
    ('Bianca', 'Hortolandia', 4, null),
    ('César', 'Sao Paulo', 5, null),
    ('Lívia', 'Campinas', 1, null),
    ('Hugo', 'Valinhos', 2, null),
    ('Tatiane', 'Vinhedo', 3, null),
    ('Renata', 'Hortolandia', 4, null),
    ('Cristiano', 'Sao Paulo', 5, null),
    ('Evelyn', 'Campinas', 1, null),
    ('Rita', 'Valinhos', 2, null),
    ('Alessandro', 'Vinhedo', 3, null),
    ('Cláudia', 'Hortolandia', 4, null),
    ('Paulo', 'Sao Paulo', 5, null),
    ('Viviane', 'Campinas', 1, null),
    ('Jonas', 'Valinhos', 2, null),
    ('Marcos', 'Vinhedo', 3, null),
    ('Tatiana', 'Hortolandia', 4, null),
    ('Cristina', 'Sao Paulo', 5, null),
    ('Leandro', 'Campinas', 1, null),
    ('Flávia', 'Valinhos', 2, null),
    ('Douglas', 'Vinhedo', 3, null),
    ('Mônica', 'Hortolandia', 4, null),
    ('Ruan', 'Sao Paulo', 5, null),
    ('Jéssica', 'Campinas', 1, null),
    ('Samuel', 'Valinhos', 2, null),
    ('Kelly', 'Vinhedo', 3, null),
    ('Antônio', 'Hortolandia', 4, null),
    ('Sabrina', 'Sao Paulo', 5, null),
    ('Igor', 'Campinas', 1, null),
    ('Letícia', 'Valinhos', 2, null),
    ('Vinícius', 'Vinhedo', 3, null),
    ('Tamires', 'Hortolandia', 4, null),
    ('Rafaela', 'Sao Paulo', 5, null),
    ('Matheus', 'Campinas', 1, null),
    ('Luiz', 'Valinhos', 2, null),
    ('Joana', 'Vinhedo', 3, null),
    ('Catarina', 'Hortolandia', 4, null),
    ('Alberto', 'Sao Paulo', 5, null),
    ('Otávia', 'Campinas', 1, null),
    ('Fabrício', 'Valinhos', 2, null),
    ('Clarice', 'Vinhedo', 3, null),
    ('Renan', 'Hortolandia', 4, null),
    ('Julio', 'Sao Paulo', 5, null),
    ('Marina', 'Campinas', 1, null);